apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  labels:
    app: canary-example
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: canary-example
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: canary-example
        version: v1
    spec:
      containers:
      - name: canary
        image: gijsvandulmen/fixed:latest
        imagePullPolicy: Always
        env:
          - name: STATUS_CODE
            value: "200"
          - name: CONTENTS
            value: "Primary OK"
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "1000Mi"
        ports:
          - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /live
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 600
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
        # env:
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: svc-canary
  labels:
    app: canary-example
spec:
  ports:
  - port: 8082
    name: http
  selector:
    app: canary-example
    version: v1