apiVersion: v1
kind: Secret
metadata:
    name: kiali
    namespace: istio-system
    labels:
        app: kiali
type: Opaque
data:
    # echo -n 'kiali' | base64 
    username: a2lhbGk=
    # echo -n 'verysecretpassword' | base64
    passphrase: dmVyeXNlY3JldHBhc3N3b3Jk