apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocksolid
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: rocksolid
        image: gijsvandulmen/echoserver:latest